winget install -e --id Discord.Discord
winget install -e --id Microsoft.VisualStudioCode
winget install -e --id Zoom.Zoom
winget install -e --id Git.Git
winget install -e --id Python.Python
winget install -e --id Microsoft.Teams
winget install -e --id qBittorrent.qBittorrent
winget install -e --id Mozilla.Firefox
winget install -e --id TechPowerUp.GPU-Z
winget install -e --id Telegram.TelegramDesktop
winget install -e --id Julialang.Julia
winget install -e --id Dropbox.Dropbox
winget install -e --id Audacity.Audacity
winget install -e --id Microsoft.VC++2015-2019Redist-x86
winget install -e --id Microsoft.PowerToys
winget install -e --id Google.Chrome
winget install -e --id 7zip.7zip
winget install -e --id Microsoft.WindowsTerminal
winget install -e --id ActivityWatch.ActivityWatch
winget install -e --id DominikReichl.KeePass
winget install -e --id Valve.Steam
winget install -e --id EpicGames.EpicGamesLauncher
winget install -e --id Microsoft.VisualStudio.Community
winget install -e --id Rust.rustup
winget install -e --id OBSProject.OBSStudio
winget install -e --id ShareX.ShareX
winget install -e --id TUG.TeXLive
winget install -e --id Zotero.Zotero
winget install -e --id GIMP.GIMP
winget install -e --id JohnMacFarlane.Pandoc
winget install -e --id Autodesk.Fusion360
winget install -e --id Caprine.Caprine
winget install -e --id VideoLAN.VLC
winget install -e --id Joplin.Joplin
